// Human-readable timeline of the analytics/business events decoded from a
// recording. Companion to the API flow doc — same recording, different lens.

function clip(s, max = 90) {
  return s.length > max ? s.slice(0, max) + '…' : s;
}

function inlineParams(params) {
  if (!params || !Object.keys(params).length) return '';
  try { return clip(JSON.stringify(params)); } catch { return ''; }
}

function timeOfDay(iso) {
  return iso ? iso.slice(11, 23) : '';
}

function offset(ms) {
  if (ms == null) return '';
  return ms < 1000 ? `+${ms}ms` : `+${(ms / 1000).toFixed(1)}s`;
}

export function toEventsMarkdown({ events, byProvider, startedAt, stoppedAt, target }, options = {}) {
  const title = options.title
    ? `Analytics events — ${options.title}`
    : `Analytics events — ${target?.title || target?.url || 'recording'}`;
  const lines = [];

  lines.push(`# ${title}`);
  lines.push('');
  lines.push(`> Recorded ${startedAt || ''} → ${stoppedAt || ''}`);
  if (target?.url) lines.push(`> Page: ${target.url}`);
  lines.push('');

  lines.push('## Overview');
  lines.push('');
  lines.push(`- **Events fired:** ${events.length}`);
  const providers = Object.entries(byProvider || {}).sort((a, b) => b[1] - a[1]);
  if (providers.length) {
    lines.push(`- **Providers:** ${providers.map(([p, n]) => `\`${p}\` ×${n}`).join(', ')}`);
  }
  lines.push('');

  lines.push('## Timeline');
  lines.push('');
  lines.push('| # | Time | Offset | Provider | Event | Params |');
  lines.push('|---|------|--------|----------|-------|--------|');
  events.forEach((e, i) => {
    lines.push(`| ${i + 1} | ${timeOfDay(e.at)} | ${offset(e.offsetMs)} | ${e.provider} | \`${e.event}\` | ${inlineParams(e.params)} |`);
  });
  lines.push('');

  lines.push('## Event details');
  lines.push('');
  events.forEach((e, i) => {
    lines.push(`### ${i + 1}. \`${e.event}\` (${e.provider})`);
    lines.push('');
    if (e.at) lines.push(`- **Fired at:** ${e.at} (${offset(e.offsetMs)} into the recording)`);
    lines.push(`- **Sent to:** \`${e.host}\``);
    if (e.tab > 0) lines.push(`- **Tab:** popup/new tab #${e.tab}`);
    if (e.params && Object.keys(e.params).length) {
      lines.push('');
      lines.push('```json');
      lines.push(JSON.stringify(e.params, null, 2));
      lines.push('```');
    }
    lines.push('');
  });

  lines.push('---');
  lines.push('_Generated by browser-flow-tracker. Full beacon payloads are in the accompanying `.events.json`._');
  lines.push('');
  return lines.join('\n');
}
