// Generates a first-draft Markdown flow document from a normalized flow.
// Claude/Cursor can read the JSON for detail; this is the human-readable draft.

function shortBody(body, isJson, max = 600) {
  if (body == null || body === '') return '';
  let s = isJson ? JSON.stringify(body, null, 2) : String(body);
  if (s.length > max) s = s.slice(0, max) + '\n… [truncated]';
  return s;
}

function safeLabel(s) {
  return String(s).replace(/[^\w./:-]/g, '_').slice(0, 40);
}

export function toMarkdown(session, options = {}) {
  const { flow, stats } = session;
  const apiFlow = flow.filter((e) => e.category === 'api' || e.category === 'websocket' || e.category === 'sse');
  const title = options.title || `API Flow — ${session.target?.title || session.target?.url || 'recording'}`;
  const lines = [];

  lines.push(`# ${title}`);
  lines.push('');
  lines.push(`> Recorded ${session.startedAt || ''} → ${session.stoppedAt || ''}`);
  if (session.target?.url) lines.push(`> Page: ${session.target.url}`);
  lines.push('');

  // Overview
  lines.push('## Overview');
  lines.push('');
  lines.push(`- **API calls captured:** ${apiFlow.length}`);
  lines.push(`- **Total requests seen:** ${stats.totalCaptured} (${stats.droppedCount} filtered as noise)`);
  const hosts = Object.entries(stats.byHost).sort((a, b) => b[1] - a[1]);
  if (hosts.length) {
    lines.push(`- **Hosts:** ${hosts.map(([h, n]) => `\`${h}\` (${n})`).join(', ')}`);
  }
  const statuses = Object.entries(stats.byStatus).sort();
  if (statuses.length) {
    lines.push(`- **Status codes:** ${statuses.map(([s, n]) => `${s}×${n}`).join(', ')}`);
  }
  lines.push('');

  // Sequence diagram
  lines.push('## Sequence diagram');
  lines.push('');
  lines.push('```mermaid');
  lines.push('sequenceDiagram');
  lines.push('    participant B as Browser');
  const participants = new Map();
  for (const e of apiFlow) {
    if (!participants.has(e.host)) participants.set(e.host, `S${participants.size}`);
  }
  for (const [host, id] of participants) lines.push(`    participant ${id} as ${host}`);
  for (const e of apiFlow) {
    const id = participants.get(e.host);
    const label = `${e.method} ${safeLabel(e.path)}`;
    lines.push(`    B->>${id}: ${label}`);
    const st = e.failed ? `FAILED ${e.errorText || ''}` : `${e.status || '?'} ${e.statusText || ''}`.trim();
    lines.push(`    ${id}-->>B: ${st}`);
  }
  lines.push('```');
  lines.push('');

  // Ordered endpoint table
  lines.push('## Call sequence');
  lines.push('');
  lines.push('| # | Method | Endpoint | Status | Time |');
  lines.push('|---|--------|----------|--------|------|');
  apiFlow.forEach((e, i) => {
    const status = e.failed ? `✗ ${e.errorText || 'failed'}` : e.status || '';
    const time = e.durationMs != null ? `${e.durationMs}ms` : '';
    lines.push(`| ${i + 1} | ${e.method} | \`${e.host}${e.path}\` | ${status} | ${time} |`);
  });
  lines.push('');

  // Detailed breakdown
  lines.push('## Call details');
  lines.push('');
  apiFlow.forEach((e, i) => {
    lines.push(`### ${i + 1}. ${e.method} ${e.path}`);
    lines.push('');
    lines.push(`- **URL:** \`${e.url}\``);
    if (e.tab > 0) lines.push(`- **Tab:** popup/new tab #${e.tab}${e.tabUrl ? ` (\`${e.tabUrl}\`)` : ''}`);
    lines.push(`- **Status:** ${e.failed ? `✗ ${e.errorText}` : `${e.status || ''} ${e.statusText || ''}`}`);
    if (e.durationMs != null) lines.push(`- **Duration:** ${e.durationMs}ms`);
    if (e.initiator) lines.push(`- **Initiated by:** ${e.initiator}`);
    if (e.query && Object.keys(e.query).length) {
      lines.push(`- **Query params:** \`${JSON.stringify(e.query)}\``);
    }
    const reqStr = shortBody(e.requestBody, e.requestBodyIsJson);
    if (reqStr) {
      lines.push('');
      lines.push('**Request body:**');
      lines.push('```json');
      lines.push(reqStr);
      lines.push('```');
    }
    const resStr = shortBody(e.responseBody, e.responseBodyIsJson);
    if (resStr) {
      lines.push('');
      lines.push('**Response body:**');
      lines.push('```json');
      lines.push(resStr);
      lines.push('```');
    }
    lines.push('');
  });

  lines.push('---');
  lines.push('_Draft generated by browser-flow-tracker. Refine with Claude/Cursor using the accompanying `.flow.json`._');
  lines.push('');
  return lines.join('\n');
}
